# Config incial
max_attepms: 150000
namespace: TSN
file_name_out: C:\Users\USER\AppData\Roaming\MetaQuotes\Terminal\D0E8209F77C8CF37AD8BF550E51FF075\MQL5\Shared Projects\FullMt5McpByLeo\Src\EnumReg\Table.mqh
table_prefix: g_fullmt5mcpbyleo_enum_reg
copyright: Copyright 2026, Niquel Mendoza
link: https://www.mql5.com/
func_name: TempHashCustom
def_name_table_size: FULLMTCPMCP_ENUMREG_TABLE_SIZE
def_bucket_size_name: FULLMTCPMCP_ENUMREG_BUCKET_SIZE
invalid_value: -1
comment_funct: true 

# En bin no guardaremos nada usaremos directo el MQH

# Random 
random:
  type: PHASH_RANDOM_MATH_XOSHIRO256
  config: 
    seed: 0x145615123

# Hash    
hash:
  type: TSN_PHASH_TYPE_FNV1A_64
  config: 
    basis: def
    prime: def

# Final hash
final_hash: HASH_UL1_SPLITMIX

# Algoritm
perfect_hash:
  elements_por_bucket: 3
  load_factor: 0.81

# Main
map_use_value: true
map: {
  MCPFUNC_TIME_GMT: 0,
  MCPFUNC_TIME_CURRENT: 1,
  MCPFUNC_TIME_LOCAL: 2,
  MCPFUNC_TIME_SERVER: 3,
  MTTESTER_MODELADO_EVERY_TICK: 0,
  MTTESTER_MODELADO_OCHLM1: 1,
  MTTESTER_MODELADO_ONLY_OPEN: 2,
  MTTESTER_MODELADO_REAL_TICK: 4,
  MCPFUNC_COPY_DATA_CLOSE: 0,
  MCPFUNC_COPY_DATA_OPEN: 1,
  MCPFUNC_COPY_DATA_HIGH: 2,
  MCPFUNC_COPY_DATA_LOW: 3,
  MCPFUNC_COPY_DATA_TICK_VOLUME: 4,
  MCPFUNC_COPY_DATA_REAL_VOLUME: 5,
  MCPFUNC_COPY_DATA_TIME: 6,
  MCPFUNC_COPY_DATA_SPREAD: 7,
  MTTESTER_OPTMIZATION_NONE: 0,
  MTTESTER_OPTIMIZAITON_SLOW: 1,
  MTTESTER_OPTIMIZACION_AG_FAST: 2,
  MTTESTER_OPTIMIZAION_ALL_MARKET_WATH: 4,
  MTTESTER_OPTCRIT_BALANCE_MAX: 0,
  MTTESTER_OPTCRIT_PROFIT_FACTOR_MAX: 1,
  MTTESTER_OPTCRIT_EXPECTED_PAYOFF_MAX: 2,
  MTTESTER_OPTCRIT_DRAWDOWN_MIN: 3,
  MTTESTER_OPTCRIT_RECOVERY_FACTOR_MAX: 4,
  MTTESTER_OPTCRIT_SHARPE_RATIO_MAX: 5,
  MTTESTER_OPTCRIT_CUSTOM_MAX: 6,
  MTTESTER_OPTCRIT_COMPLEX_CRITERION_MAX: 7,
  MTTESTER_FORWARD_NONE: 0,
  MTTESTER_FORWARD_HALF: 1,
  MTTESTER_FORWARD_THIRD: 2,
  MTTESTER_FORWARD_QUARTER: 3,
  MTTESTER_FORWARD_CUSTOM: 4,
  MCPFUNC_TESTER_GET_SUMMARY: 0,
  MCPFUNC_TESTER_GET_BALANCE_HISTORY: 1,
  MCPFUNC_TESTER_GET_EQUITY_HISTORY: 2,
  MCPFUNC_TESTER_GET_DEALS_HISTORY: 3,
  MCPFUNC_CALCORDER_CALCULATE_SL_WITH_LOT: 0,
  MCPFUNC_CALCORDER_MONEY_TO_POINTS: 1,
  MCPFUNC_CALCORDER_GET_LOTE_BY_RISK_MONEY_AND_SL_POINTS: 2,
  MCPFUNC_CALCORDER_GET_MAX_LOTE_TO_TRADE: 3,
  MCPFUNC_CALCORDER_GET_LOTE_BY_ONLY_RISK_MONEY: 4,
  MCPFUNC_IND_ACTION_CREATE: 0,
  MCPFUNC_IND_ACTION_TOTAL: 1,
  MCPFUNC_IND_ACTION_GET_HANDLES_NAMES: 2,
  MCPFUNC_IND_ACTION_REMOVE: 3,
  MCPFUNC_IND_ACTION_GET_HANDLE_BY_NAME: 4,
  MCPFUNC_IND_ACTION_GET_PARAMETERS: 5,
  MCPFUNC_IND_ACTION_ADD: 6,
  MCPFUNC_IND_ACTION_COPYBUFFER: 7,
  MCPFUNC_CHARTIND_TOTAL: 0,
  MCPFUNC_CHARTIND_SHORT_NAME: 1,
  MCPFUNC_CHARTIND_ADD: 2,
  MCPFUNC_CHARTIND_DELETE: 3
}